### ISSUE TITLE
Error  please see

### ISSUE THREAD

**Issue by sibjac** [xzaviourr/BrokerTerminal_WithExcel#1]
it runs fine upto here, after that nothing happens
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...
Alice Blue Logger - INFO - Waiting for socket streaming to start ...

**Comment by xzaviourr** [comment]
@sibjac You need to add your alice blue credentials in the credentials file to run this application.
